import Head from "next/head";
import Script from "next/script";
import Header from "../components/Header";
import HeroSection from "../components/HeroSection";

export default function Home() {
  return (
    <div className="h-screen overflow-scroll text-white bg-black snap-y snap-mandatory">
      <Head>
        <title>Aman Soni</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          rel="stylesheet"
          href="https://unpkg.com/swiper@8/swiper-bundle.min.css"
        />
      </Head>

      <Script src="https://unpkg.com/@rive-app/webgl" />
      <Script src="https://unpkg.com/swiper@8/swiper-bundle.min.js" />

      {/* Header */}
      <Header />
      <HeroSection />
    </div>
  );
}
